//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourSSecurity.DataLayer
{
    using System;
    using FourSSecurity.Entity;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FourSSecurityDBEntities : DbContext
    {
        public FourSSecurityDBEntities()
            : base("name=FourSSecurityDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
    }
}
